matrix:
  include:
    - language: node_js
      node_js: 12.6.0
      before_script:
        - cd client
        - npm i
      script:
        - npm test

    - language: go
      go: "1.13"
      env:
        - GO111MODULE=on
      go_import_path: server/internal
      before_script:
        - cd server
      script:
      - sh test.sh

notifications:
  email:
    if: branch = master
    recipients:
       - jngincorporated@gmail.com
    on_success: never
    on_failure: always