matrix:
  include:
    - language: node_js
      node_js: 12.6.0
      before_script:
        - cd client
        - npm i
      script:
        - npm test

    - language: go
      go: "1.13"
      before_script:
        - cd server
        - go mod init githubapp.tld/server
        - go build -o main . 
      script:
        - sh test.sh

# notifications:
#   email:
#     - jngincorporated@gmail.com
